import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { getMonthlyReports } from "../api/dashboardApi";

function MonthlyReport() {
  const navigate = useNavigate();
  const [reports, setReports] = useState([]);
  const [loading, setLoading] = useState(true);
  const [errorMessage, setErrorMessage] = useState("");

  useEffect(() => {
    const fetchReports = async () => {
      try {
        const data = await getMonthlyReports();
        setReports(data);
      } catch (error) {
        setErrorMessage(
          error.response?.data?.message || "Failed to load monthly reports."
        );
      } finally {
        setLoading(false);
      }
    };
    fetchReports();
  }, []);

  return (
    <div>
      <nav className="navbar">
        <div className="nav-brand">🪙 Smart Chit Fund</div>
        <div className="nav-links">
          <button className="btn btn-secondary" onClick={() => navigate("/admin")}>
            Admin Dashboard
          </button>
        </div>
      </nav>

      <div className="glass-container">
        <div className="view-header">
          <div className="view-title-area">
            <h1>Monthly Activity Reports</h1>
            <p className="view-subtitle">Review collection summaries and financial health metrics across all chit groups.</p>
          </div>
          <button className="btn btn-secondary" onClick={() => navigate(-1)}>Back</button>
        </div>

        {errorMessage && <div className="alert alert-danger">{errorMessage}</div>}

        {loading ? (
          <div className="text-center" style={{ padding: "3rem 0" }}>
            <p style={{ color: "var(--text-muted)" }}>Loading reports...</p>
          </div>
        ) : reports.length === 0 ? (
          <div className="glass-card text-center" style={{ padding: "4rem 2rem" }}>
            <p style={{ color: "var(--text-muted)", marginBottom: "1rem" }}>No monthly reports generated yet.</p>
            <p style={{ fontSize: "0.85rem", color: "var(--text-secondary)" }}>Reports are automatically generated by the system on the 1st of every month.</p>
          </div>
        ) : (
          <div className="glass-card mb-8">
            <h2 className="mb-4">Generated Reports Log</h2>
            <div className="table-container" style={{ border: "none", margin: 0 }}>
              <table className="modern-table">
                <thead>
                  <tr>
                    <th>Report ID</th>
                    <th>Chit Group</th>
                    <th>Month #</th>
                    <th>Collected (₹)</th>
                    <th>Pending (₹)</th>
                    <th>Paid Members</th>
                    <th>Unpaid Members</th>
                    <th className="text-right">Collection Rate</th>
                  </tr>
                </thead>
                <tbody>
                  {reports.map((report) => {
                    const expectedTotal = Number(report.monthly_installment) * (report.paid_count + report.unpaid_count);
                    const collectionRate = expectedTotal > 0 ? (Number(report.collected_amount) / expectedTotal) * 100 : 0;
                    
                    return (
                      <tr key={report.report_id}>
                        <td><code>#{report.report_id}</code></td>
                        <td>
                          <strong>{report.group_name}</strong><br/>
                          <span style={{ fontSize: '0.8rem', color: 'var(--text-muted)' }}>Chit #{report.chit_id}</span>
                        </td>
                        <td>Month {report.month_number}</td>
                        <td style={{ color: "var(--success)" }}>₹{Number(report.collected_amount).toLocaleString("en-IN")}</td>
                        <td style={{ color: report.pending_amount > 0 ? "var(--danger)" : "var(--text-muted)" }}>
                          ₹{Number(report.pending_amount).toLocaleString("en-IN")}
                        </td>
                        <td><span className="badge badge-success">{report.paid_count}</span></td>
                        <td>
                          {report.unpaid_count > 0 ? (
                            <span className="badge badge-danger">{report.unpaid_count}</span>
                          ) : (
                            <span className="badge badge-secondary">0</span>
                          )}
                        </td>
                        <td className="text-right">
                          <strong style={{ color: collectionRate >= 90 ? "var(--success)" : collectionRate >= 50 ? "var(--warning)" : "var(--danger)" }}>
                            {collectionRate.toFixed(1)}%
                          </strong>
                        </td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}

export default MonthlyReport;
